artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/rushin236/Datasets/raw/main/Adult_census_ineuron/adult.csv
  local_data_file: artifacts/data_ingestion/raw_data.csv

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  ALL_REQUIRED_FILES: ["raw_data.csv"]

data_analysis:
  local_data_file: artifacts/data_ingestion/raw_data.csv
